export const ALL_NEWPRODUCT_REQUEST = "ALL_NEWPRODUCT_REQUEST";
export const ALL_NEWPRODUCT_SUCCESS = "ALL_NEWPRODUCT_SUCCESS";
export const ALL_NEWPRODUCT_FAIL = "ALL_NEWPRODUCT_FAIL";

export const ADMIN_NEWPRODUCT_REQUEST = "ADMIN_NEWPRODUCT_REQUEST";
export const ADMIN_NEWPRODUCT_SUCCESS = "ADMIN_NEWPRODUCT_SUCCESS";
export const ADMIN_NEWPRODUCT_FAIL = "ADMIN_NEWPRODUCT_FAIL";

export const NEW_NEWPRODUCT_REQUEST = "NEW_NEWPRODUCT_REQUEST";
export const NEW_NEWPRODUCT_SUCCESS = "NEW_NEWPRODUCT_SUCCESS";
export const NEW_NEWPRODUCT_RESET = "NEW_NEWPRODUCT_RESET";
export const NEW_NEWPRODUCT_FAIL = "NEW_NEWPRODUCT_FAIL";

export const UPDATE_NEWPRODUCT_REQUEST = "UPDATE_NEWPRODUCT_REQUEST";
export const UPDATE_NEWPRODUCT_SUCCESS = "UPDATE_NEWPRODUCT_SUCCESS";
export const UPDATE_NEWPRODUCT_RESET = "UPDATE_NEWPRODUCT_RESET";
export const UPDATE_NEWPRODUCT_FAIL = "UPDATE_NEWPRODUCT_FAIL";

export const DELETE_NEWPRODUCT_REQUEST = "DELETE_NEWPRODUCT_REQUEST";
export const DELETE_NEWPRODUCT_SUCCESS = "DELETE_NEWPRODUCT_SUCCESS";
export const DELETE_NEWPRODUCT_RESET = "DELETE_NEWPRODUCT_RESET";
export const DELETE_NEWPRODUCT_FAIL = "DELETE_NEWPRODUCT_FAIL";

export const NEWPRODUCT_DETAILS_REQUEST = "NEWPRODUCT_DETAILS_REQUEST";
export const NEWPRODUCT_DETAILS_SUCCESS = "NEWPRODUCT_DETAILS_SUCCESS";
export const NEWPRODUCT_DETAILS_FAIL = "NEWPRODUCT_DETAILS_FAIL";

export const NEW_NEWREVIEW_REQUEST = "NEW_NEWREVIEW_REQUEST";
export const NEW_NEWREVIEW_SUCCESS = "NEW_NEWREVIEW_SUCCESS";
export const NEW_NEWREVIEW_RESET = "NEW_NEWREVIEW_RESET";
export const NEW_NEWREVIEW_FAIL = "NEW_NEWREVIEW_FAIL";

export const ALL_NEWREVIEW_REQUEST = "ALL_NEWREVIEW_REQUEST";
export const ALL_NEWREVIEW_SUCCESS = "ALL_NEWREVIEW_SUCCESS";
export const ALL_NEWREVIEW_FAIL = "ALL_NEWREVIEW_FAIL";

export const DELETE_NEWREVIEW_REQUEST = "DELETE_NEWREVIEW_REQUEST";
export const DELETE_NEWREVIEW_SUCCESS = "DELETE_NEWREVIEW_SUCCESS";
export const DELETE_NEWREVIEW_RESET = "DELETE_NEWREVIEW_RESET";
export const DELETE_NEWREVIEW_FAIL = "DELETE_NEWREVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
